<h3>Add new record</h3>

<a href="<?=$basePath;?>service/<?=$service_id;?>" class="btn btn-outline-info my-2">Back</a>

<form action="<?=$basePath;?>service/insert/<?=$service_id;?>" method="post" class="ajax service">
    <div class="form-group">
        <label for="record_type">Record type</label>
        <select name="type" id="record_type" class="form-control">
            <option value="A">A</option>
            <option value="AAAA">AAAA</option>
            <option value="MX">MX</option>
            <option value="ANAME">ANAME</option>
            <option value="CNAME">CNAME</option>
            <option value="NS" disabled>NS</option>
            <option value="TXT">TXT</option>
            <option value="SRV">SRV</option>
        </select>
    </div>
    <div class="form-group">
        <label for="name">Subdomain name</label>
        <div class="input-group">
            <input type="text" name="name" id="name" class="form-control" required>
            <div class="input-group-append">
                <span class="input-group-text">.<?=$service_id;?></span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label for="content">IPv4 address</label>
        <input type="text" name="content" id="content" class="form-control" placeholder="127.0.0.1" required>
    </div>
    <div class="form-group">
        <label for="ttl">TTL (optional)</label>
        <div class="input-group">
            <input type="number" name="ttl" id="ttl" class="form-control" placeholder="600">
            <div class="input-group-append">
                <span class="input-group-text">sec</span>
            </div>
        </div>
    </div>

    <button type="submit" class="btn-primary">Add</button>
    <button type="reset" class="btn-secondary">Reset</button>
</form>