<h1>Add new record</h1>

<form action="<?=$basePath;?>service/test" method="post">
    <div class="form-group">
        <label for="record_type">Record type</label>
        <select name="type" id="record_type" class="form-control">
            <option value="A">A</option>
            <option value="AAAA">AAAA</option>
            <option value="MX">MX</option>
            <option value="ANAME">ANAME</option>
            <option value="CNAME">CNAME</option>
            <option value="NS">NS</option>
            <option value="TXT">TXT</option>
            <option value="SRV">SRV</option>
        </select>
    </div>
    <div class="form-group">
        <label for="name">Subdomain name</label>
        <input type="text" name="name" id="name" class="form-control" required>
    </div>
    <div class="form-group">
        <label for="content">IPv4 address</label>
        <input type="text" name="content" id="content" class="form-control" placeholder="127.0.0.1" required>
    </div>
    <div class="form-group">
        <label for="ttl">TTL</label>
        <input type="number" name="ttl" id="ttl" class="form-control" placeholder="600">
    </div>

    <button type="submit" class="btn-primary">Add</button>
</form>